### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-vscode-tools#1]
```[tasklist]
### Tasks
- [x] Update README.md.
- [x] Add Pulumi YAML as an extension dependency.
- [x] Block on core contribution: https://github.com/pulumi/pulumi/pull/14516
- [x] Write a command to enumerate the stacks, and polish the launch configuration experience
- [x] Support interactive stack selection
- [x] Don't hardcode the `dev` stack in the dynamic launch configuration.
- [x] Add useful configuration settings, e.g. an override for `PULUMI_HOME`.
- [x] Build a [private package](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) for local testing of the extension.
- [x] Write a "dogfooding" document
- [x] Cleanup any remaining template code.
- [x] Remove "hello world" command
- [x] Automatically install Pulumi (https://github.com/microsoft/vscode-discussions/discussions/516)
- [x] Unify the ESC bits
- [x] Publish to the marketplace.
- [x] bundling
- [x] license update
- [x] Make this repository be public.
- [ ] Write extension tests.
- [ ] Add some documentation to the Pulumi site.
- [ ] Write a blog post to announce the feature.
- [ ] Show an useful error when pulumi isn't logged in
- [ ] Support Pulumi DIY
- [ ] Add useful launch configuration properties, e.g.`target`.
- [ ] tweak for https://github.com/pulumi/pulumi/pull/16783
```

**Comment by mjeffryes** [comment]
We'll create some tickets for follow ups
